services:
  web:
    build: .
    container_name: kawou_24606
    command: >
      sh -c "
      python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "127.0.0.1:25606:8000"
    volumes:
      - ./mru_fx:/app

  # fetcher:
  #   build: .
  #   container_name: fetcher
  #   command: >
  #     sh -c "
  #     while true; do
  #       python /app/fetch_rates.py;
  #       sleep 86400;
  #     done
  # #     "
  #   volumes:
  #     - ./fetcher:/app